services:
  minio:
    container_name: "PIERUMminio"
    image: minio/minio:latest
    ports:
      - "9831:9831"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin12
    command: server /data --address ":9831" --console-address ":9001"
    volumes:
      - ./vault/s3:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9831/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  etcd:
    container_name: PIERUMetcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./vault/etcd:/etcd
    command: >
      etcd --advertise-client-urls http://etcd:2379 --listen-client-urls
      http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  milvus:
    container_name: PIERUMmilvus
    image: milvusdb/milvus:v2.5.10
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      COMMON_STORAGE_TYPE: remote
      MINIO_ADDRESS: PIERUMminio:9831
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_ACCESS_KEY: minioadmin12
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./vault/milvus:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: always