@echo off
echo [LOG] Updating Go dependencies (go get -u ./...)...
call go get -u ./...

echo [LOG] Tidying go.mod (go mod tidy)...
call go mod tidy

echo [LOG] Done! Dependencies are up to date and go.mod is clean.
