package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"app/server/server/graph/model"
	"context"
	"fmt"
)

// AskChessCoach is the resolver for the askChessCoach field.
func (r *mutationResolver) AskChessCoach(ctx context.Context, input *model.ChessStudentRequest) (*model.ChessCoachPayload, error) {
	panic(fmt.Errorf("not implemented: AskChessCoach - askChessCoach"))
}

// Config is the resolver for the config field.
func (r *mutationResolver) Config(ctx context.Context, input *model.IConfigRequest) (*model.IConfigResp, error) {
	panic(fmt.Errorf("not implemented: Config - config"))
}

// InitCoachSuggestions is the resolver for the initCoachSuggestions field.
func (r *queryResolver) InitCoachSuggestions(ctx context.Context, input *model.ChessStudentRequest) ([]*model.OnChessCoachReply, error) {
	panic(fmt.Errorf("not implemented: InitCoachSuggestions - initCoachSuggestions"))
}

// ChessCoachReply is the resolver for the chessCoachReply field.
func (r *subscriptionResolver) ChessCoachReply(ctx context.Context, input *model.ChessStudentRequest) (<-chan *model.OnChessCoachReply, error) {
	panic(fmt.Errorf("not implemented: ChessCoachReply - chessCoachReply"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
