// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: rum.proto

package rumrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ISequence struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Profile string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	// string service = 2;
	// int32 rank = 3;
	Input         []byte `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISequence) Reset() {
	*x = ISequence{}
	mi := &file_rum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISequence) ProtoMessage() {}

func (x *ISequence) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISequence.ProtoReflect.Descriptor instead.
func (*ISequence) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{0}
}

func (x *ISequence) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *ISequence) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type IPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ISequence             `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Push          bool                   `protobuf:"varint,3,opt,name=push,proto3" json:"push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPost) Reset() {
	*x = IPost{}
	mi := &file_rum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPost) ProtoMessage() {}

func (x *IPost) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPost.ProtoReflect.Descriptor instead.
func (*IPost) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{1}
}

func (x *IPost) GetProfile() *ISequence {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *IPost) GetPush() bool {
	if x != nil {
		return x.Push
	}
	return false
}

type IPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Kit           string                 `protobuf:"bytes,2,opt,name=kit,proto3" json:"kit,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Dispatcher    string                 `protobuf:"bytes,4,opt,name=dispatcher,proto3" json:"dispatcher,omitempty"`
	Event         string                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPackageRequest) Reset() {
	*x = IPackageRequest{}
	mi := &file_rum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPackageRequest) ProtoMessage() {}

func (x *IPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPackageRequest.ProtoReflect.Descriptor instead.
func (*IPackageRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{2}
}

func (x *IPackageRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *IPackageRequest) GetKit() string {
	if x != nil {
		return x.Kit
	}
	return ""
}

func (x *IPackageRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *IPackageRequest) GetDispatcher() string {
	if x != nil {
		return x.Dispatcher
	}
	return ""
}

func (x *IPackageRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type IPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Name          *IPackageRequest       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Succeed       *ISucceed              `protobuf:"bytes,3,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Package       []byte                 `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPackage) Reset() {
	*x = IPackage{}
	mi := &file_rum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPackage) ProtoMessage() {}

func (x *IPackage) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPackage.ProtoReflect.Descriptor instead.
func (*IPackage) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{3}
}

func (x *IPackage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IPackage) GetName() *IPackageRequest {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *IPackage) GetSucceed() *ISucceed {
	if x != nil {
		return x.Succeed
	}
	return nil
}

func (x *IPackage) GetPackage() []byte {
	if x != nil {
		return x.Package
	}
	return nil
}

type ISucceed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       bool                   `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISucceed) Reset() {
	*x = ISucceed{}
	mi := &file_rum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISucceed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISucceed) ProtoMessage() {}

func (x *ISucceed) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISucceed.ProtoReflect.Descriptor instead.
func (*ISucceed) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{4}
}

func (x *ISucceed) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          []*IPost               `protobuf:"bytes,1,rep,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPostRequest) Reset() {
	*x = IPostRequest{}
	mi := &file_rum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPostRequest) ProtoMessage() {}

func (x *IPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPostRequest.ProtoReflect.Descriptor instead.
func (*IPostRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{5}
}

func (x *IPostRequest) GetPost() []*IPost {
	if x != nil {
		return x.Post
	}
	return nil
}

type IPostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       *ISucceed              `protobuf:"bytes,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPostResponse) Reset() {
	*x = IPostResponse{}
	mi := &file_rum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPostResponse) ProtoMessage() {}

func (x *IPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPostResponse.ProtoReflect.Descriptor instead.
func (*IPostResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{6}
}

func (x *IPostResponse) GetSucceed() *ISucceed {
	if x != nil {
		return x.Succeed
	}
	return nil
}

type IMonitorTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           []string               `protobuf:"bytes,1,rep,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMonitorTagRequest) Reset() {
	*x = IMonitorTagRequest{}
	mi := &file_rum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMonitorTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMonitorTagRequest) ProtoMessage() {}

func (x *IMonitorTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMonitorTagRequest.ProtoReflect.Descriptor instead.
func (*IMonitorTagRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{7}
}

func (x *IMonitorTagRequest) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

type IMonitorTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       *ISucceed              `protobuf:"bytes,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMonitorTagResponse) Reset() {
	*x = IMonitorTagResponse{}
	mi := &file_rum_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMonitorTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMonitorTagResponse) ProtoMessage() {}

func (x *IMonitorTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMonitorTagResponse.ProtoReflect.Descriptor instead.
func (*IMonitorTagResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{8}
}

func (x *IMonitorTagResponse) GetSucceed() *ISucceed {
	if x != nil {
		return x.Succeed
	}
	return nil
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Release       bool                   `protobuf:"varint,1,opt,name=release,proto3" json:"release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_rum_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseRequest) GetRelease() bool {
	if x != nil {
		return x.Release
	}
	return false
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeed       *ISucceed              `protobuf:"bytes,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_rum_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseResponse) GetSucceed() *ISucceed {
	if x != nil {
		return x.Succeed
	}
	return nil
}

type IConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activate      bool                   `protobuf:"varint,1,opt,name=activate,proto3" json:"activate,omitempty"`
	Swap          *ISwap                 `protobuf:"bytes,2,opt,name=swap,proto3" json:"swap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IConfig) Reset() {
	*x = IConfig{}
	mi := &file_rum_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IConfig) ProtoMessage() {}

func (x *IConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IConfig.ProtoReflect.Descriptor instead.
func (*IConfig) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{11}
}

func (x *IConfig) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

func (x *IConfig) GetSwap() *ISwap {
	if x != nil {
		return x.Swap
	}
	return nil
}

type ISwap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	With          string                 `protobuf:"bytes,1,opt,name=with,proto3" json:"with,omitempty"`
	Current       string                 `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	Swap          bool                   `protobuf:"varint,3,opt,name=swap,proto3" json:"swap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ISwap) Reset() {
	*x = ISwap{}
	mi := &file_rum_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ISwap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ISwap) ProtoMessage() {}

func (x *ISwap) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ISwap.ProtoReflect.Descriptor instead.
func (*ISwap) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{12}
}

func (x *ISwap) GetWith() string {
	if x != nil {
		return x.With
	}
	return ""
}

func (x *ISwap) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *ISwap) GetSwap() bool {
	if x != nil {
		return x.Swap
	}
	return false
}

type IConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IConfigResponse) Reset() {
	*x = IConfigResponse{}
	mi := &file_rum_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IConfigResponse) ProtoMessage() {}

func (x *IConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IConfigResponse.ProtoReflect.Descriptor instead.
func (*IConfigResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{13}
}

func (x *IConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *IConfigResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

type IDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDocRequest) Reset() {
	*x = IDocRequest{}
	mi := &file_rum_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDocRequest) ProtoMessage() {}

func (x *IDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDocRequest.ProtoReflect.Descriptor instead.
func (*IDocRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{14}
}

type IDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doc           string                 `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Succeed       bool                   `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDocResponse) Reset() {
	*x = IDocResponse{}
	mi := &file_rum_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDocResponse) ProtoMessage() {}

func (x *IDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDocResponse.ProtoReflect.Descriptor instead.
func (*IDocResponse) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{15}
}

func (x *IDocResponse) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (x *IDocResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

func (x *IDocResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Config         *IConfig               `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ProfileName    string                 `protobuf:"bytes,2,opt,name=profileName,proto3" json:"profileName,omitempty"`
	KitName        string                 `protobuf:"bytes,3,opt,name=kitName,proto3" json:"kitName,omitempty"`
	ServiceName    string                 `protobuf:"bytes,4,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	DispatcherName string                 `protobuf:"bytes,5,opt,name=dispatcherName,proto3" json:"dispatcherName,omitempty"`
	EventName      string                 `protobuf:"bytes,6,opt,name=eventName,proto3" json:"eventName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IConfigRequest) Reset() {
	*x = IConfigRequest{}
	mi := &file_rum_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IConfigRequest) ProtoMessage() {}

func (x *IConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rum_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IConfigRequest.ProtoReflect.Descriptor instead.
func (*IConfigRequest) Descriptor() ([]byte, []int) {
	return file_rum_proto_rawDescGZIP(), []int{16}
}

func (x *IConfigRequest) GetConfig() *IConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *IConfigRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *IConfigRequest) GetKitName() string {
	if x != nil {
		return x.KitName
	}
	return ""
}

func (x *IConfigRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *IConfigRequest) GetDispatcherName() string {
	if x != nil {
		return x.DispatcherName
	}
	return ""
}

func (x *IConfigRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

var File_rum_proto protoreflect.FileDescriptor

const file_rum_proto_rawDesc = "" +
	"\n" +
	"\trum.proto\x12\x06rumrpc\";\n" +
	"\tISequence\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\"H\n" +
	"\x05IPost\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.rumrpc.ISequenceR\aprofile\x12\x12\n" +
	"\x04push\x18\x03 \x01(\bR\x04push\"\x8d\x01\n" +
	"\x0fIPackageRequest\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x10\n" +
	"\x03kit\x18\x02 \x01(\tR\x03kit\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1e\n" +
	"\n" +
	"dispatcher\x18\x04 \x01(\tR\n" +
	"dispatcher\x12\x14\n" +
	"\x05event\x18\x05 \x01(\tR\x05event\"\x93\x01\n" +
	"\bIPackage\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\x04name\x18\x02 \x01(\v2\x17.rumrpc.IPackageRequestR\x04name\x12*\n" +
	"\asucceed\x18\x03 \x01(\v2\x10.rumrpc.ISucceedR\asucceed\x12\x18\n" +
	"\apackage\x18\x04 \x01(\fR\apackage\"$\n" +
	"\bISucceed\x12\x18\n" +
	"\asucceed\x18\x01 \x01(\bR\asucceed\"1\n" +
	"\fIPostRequest\x12!\n" +
	"\x04post\x18\x01 \x03(\v2\r.rumrpc.IPostR\x04post\";\n" +
	"\rIPostResponse\x12*\n" +
	"\asucceed\x18\x01 \x01(\v2\x10.rumrpc.ISucceedR\asucceed\"&\n" +
	"\x12IMonitorTagRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x03(\tR\x03tag\"A\n" +
	"\x13IMonitorTagResponse\x12*\n" +
	"\asucceed\x18\x01 \x01(\v2\x10.rumrpc.ISucceedR\asucceed\"*\n" +
	"\x0eReleaseRequest\x12\x18\n" +
	"\arelease\x18\x01 \x01(\bR\arelease\"=\n" +
	"\x0fReleaseResponse\x12*\n" +
	"\asucceed\x18\x01 \x01(\v2\x10.rumrpc.ISucceedR\asucceed\"H\n" +
	"\aIConfig\x12\x1a\n" +
	"\bactivate\x18\x01 \x01(\bR\bactivate\x12!\n" +
	"\x04swap\x18\x02 \x01(\v2\r.rumrpc.ISwapR\x04swap\"I\n" +
	"\x05ISwap\x12\x12\n" +
	"\x04with\x18\x01 \x01(\tR\x04with\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\tR\acurrent\x12\x12\n" +
	"\x04swap\x18\x03 \x01(\bR\x04swap\"A\n" +
	"\x0fIConfigResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed\"\r\n" +
	"\vIDocRequest\"P\n" +
	"\fIDocResponse\x12\x10\n" +
	"\x03doc\x18\x01 \x01(\tR\x03doc\x12\x18\n" +
	"\asucceed\x18\x02 \x01(\bR\asucceed\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xdd\x01\n" +
	"\x0eIConfigRequest\x12'\n" +
	"\x06config\x18\x01 \x01(\v2\x0f.rumrpc.IConfigR\x06config\x12 \n" +
	"\vprofileName\x18\x02 \x01(\tR\vprofileName\x12\x18\n" +
	"\akitName\x18\x03 \x01(\tR\akitName\x12 \n" +
	"\vserviceName\x18\x04 \x01(\tR\vserviceName\x12&\n" +
	"\x0edispatcherName\x18\x05 \x01(\tR\x0edispatcherName\x12\x1c\n" +
	"\teventName\x18\x06 \x01(\tR\teventName2\xe0\x04\n" +
	"\fOnRumService\x123\n" +
	"\x04POST\x12\x14.rumrpc.IPostRequest\x1a\x15.rumrpc.IPostResponse\x12E\n" +
	"\n" +
	"MonitorTag\x12\x1a.rumrpc.IMonitorTagRequest\x1a\x1b.rumrpc.IMonitorTagResponse\x12:\n" +
	"\aRelease\x12\x16.rumrpc.ReleaseRequest\x1a\x17.rumrpc.ReleaseResponse\x12F\n" +
	"\x13UpdateProfileConfig\x12\x16.rumrpc.IConfigRequest\x1a\x17.rumrpc.IConfigResponse\x12B\n" +
	"\x0fUpdateKitConfig\x12\x16.rumrpc.IConfigRequest\x1a\x17.rumrpc.IConfigResponse\x12F\n" +
	"\x13UpdateServiceConfig\x12\x16.rumrpc.IConfigRequest\x1a\x17.rumrpc.IConfigResponse\x12I\n" +
	"\x16UpdateDispatcherConfig\x12\x16.rumrpc.IConfigRequest\x1a\x17.rumrpc.IConfigResponse\x12D\n" +
	"\x11UpdateEventConfig\x12\x16.rumrpc.IConfigRequest\x1a\x17.rumrpc.IConfigResponse\x123\n" +
	"\x06GetDoc\x12\x13.rumrpc.IDocRequest\x1a\x14.rumrpc.IDocResponseB\x11Z\x0fapp/main/rumrpcb\x06proto3"

var (
	file_rum_proto_rawDescOnce sync.Once
	file_rum_proto_rawDescData []byte
)

func file_rum_proto_rawDescGZIP() []byte {
	file_rum_proto_rawDescOnce.Do(func() {
		file_rum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rum_proto_rawDesc), len(file_rum_proto_rawDesc)))
	})
	return file_rum_proto_rawDescData
}

var file_rum_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_rum_proto_goTypes = []any{
	(*ISequence)(nil),           // 0: rumrpc.ISequence
	(*IPost)(nil),               // 1: rumrpc.IPost
	(*IPackageRequest)(nil),     // 2: rumrpc.IPackageRequest
	(*IPackage)(nil),            // 3: rumrpc.IPackage
	(*ISucceed)(nil),            // 4: rumrpc.ISucceed
	(*IPostRequest)(nil),        // 5: rumrpc.IPostRequest
	(*IPostResponse)(nil),       // 6: rumrpc.IPostResponse
	(*IMonitorTagRequest)(nil),  // 7: rumrpc.IMonitorTagRequest
	(*IMonitorTagResponse)(nil), // 8: rumrpc.IMonitorTagResponse
	(*ReleaseRequest)(nil),      // 9: rumrpc.ReleaseRequest
	(*ReleaseResponse)(nil),     // 10: rumrpc.ReleaseResponse
	(*IConfig)(nil),             // 11: rumrpc.IConfig
	(*ISwap)(nil),               // 12: rumrpc.ISwap
	(*IConfigResponse)(nil),     // 13: rumrpc.IConfigResponse
	(*IDocRequest)(nil),         // 14: rumrpc.IDocRequest
	(*IDocResponse)(nil),        // 15: rumrpc.IDocResponse
	(*IConfigRequest)(nil),      // 16: rumrpc.IConfigRequest
}
var file_rum_proto_depIdxs = []int32{
	0,  // 0: rumrpc.IPost.profile:type_name -> rumrpc.ISequence
	2,  // 1: rumrpc.IPackage.name:type_name -> rumrpc.IPackageRequest
	4,  // 2: rumrpc.IPackage.succeed:type_name -> rumrpc.ISucceed
	1,  // 3: rumrpc.IPostRequest.post:type_name -> rumrpc.IPost
	4,  // 4: rumrpc.IPostResponse.succeed:type_name -> rumrpc.ISucceed
	4,  // 5: rumrpc.IMonitorTagResponse.succeed:type_name -> rumrpc.ISucceed
	4,  // 6: rumrpc.ReleaseResponse.succeed:type_name -> rumrpc.ISucceed
	12, // 7: rumrpc.IConfig.swap:type_name -> rumrpc.ISwap
	11, // 8: rumrpc.IConfigRequest.config:type_name -> rumrpc.IConfig
	5,  // 9: rumrpc.OnRumService.POST:input_type -> rumrpc.IPostRequest
	7,  // 10: rumrpc.OnRumService.MonitorTag:input_type -> rumrpc.IMonitorTagRequest
	9,  // 11: rumrpc.OnRumService.Release:input_type -> rumrpc.ReleaseRequest
	16, // 12: rumrpc.OnRumService.UpdateProfileConfig:input_type -> rumrpc.IConfigRequest
	16, // 13: rumrpc.OnRumService.UpdateKitConfig:input_type -> rumrpc.IConfigRequest
	16, // 14: rumrpc.OnRumService.UpdateServiceConfig:input_type -> rumrpc.IConfigRequest
	16, // 15: rumrpc.OnRumService.UpdateDispatcherConfig:input_type -> rumrpc.IConfigRequest
	16, // 16: rumrpc.OnRumService.UpdateEventConfig:input_type -> rumrpc.IConfigRequest
	14, // 17: rumrpc.OnRumService.GetDoc:input_type -> rumrpc.IDocRequest
	6,  // 18: rumrpc.OnRumService.POST:output_type -> rumrpc.IPostResponse
	8,  // 19: rumrpc.OnRumService.MonitorTag:output_type -> rumrpc.IMonitorTagResponse
	10, // 20: rumrpc.OnRumService.Release:output_type -> rumrpc.ReleaseResponse
	13, // 21: rumrpc.OnRumService.UpdateProfileConfig:output_type -> rumrpc.IConfigResponse
	13, // 22: rumrpc.OnRumService.UpdateKitConfig:output_type -> rumrpc.IConfigResponse
	13, // 23: rumrpc.OnRumService.UpdateServiceConfig:output_type -> rumrpc.IConfigResponse
	13, // 24: rumrpc.OnRumService.UpdateDispatcherConfig:output_type -> rumrpc.IConfigResponse
	13, // 25: rumrpc.OnRumService.UpdateEventConfig:output_type -> rumrpc.IConfigResponse
	15, // 26: rumrpc.OnRumService.GetDoc:output_type -> rumrpc.IDocResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rum_proto_init() }
func file_rum_proto_init() {
	if File_rum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rum_proto_rawDesc), len(file_rum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rum_proto_goTypes,
		DependencyIndexes: file_rum_proto_depIdxs,
		MessageInfos:      file_rum_proto_msgTypes,
	}.Build()
	File_rum_proto = out.File
	file_rum_proto_goTypes = nil
	file_rum_proto_depIdxs = nil
}
