// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.0
// source: rum.proto

package rumrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnRumService_POST_FullMethodName                   = "/rumrpc.OnRumService/POST"
	OnRumService_MonitorTag_FullMethodName             = "/rumrpc.OnRumService/MonitorTag"
	OnRumService_Release_FullMethodName                = "/rumrpc.OnRumService/Release"
	OnRumService_UpdateProfileConfig_FullMethodName    = "/rumrpc.OnRumService/UpdateProfileConfig"
	OnRumService_UpdateKitConfig_FullMethodName        = "/rumrpc.OnRumService/UpdateKitConfig"
	OnRumService_UpdateServiceConfig_FullMethodName    = "/rumrpc.OnRumService/UpdateServiceConfig"
	OnRumService_UpdateDispatcherConfig_FullMethodName = "/rumrpc.OnRumService/UpdateDispatcherConfig"
	OnRumService_UpdateEventConfig_FullMethodName      = "/rumrpc.OnRumService/UpdateEventConfig"
	OnRumService_GetDoc_FullMethodName                 = "/rumrpc.OnRumService/GetDoc"
)

// OnRumServiceClient is the client API for OnRumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OnRumService provides control plane services
// activate:- only if present & is deactive
// deactivate:- only if present & is active
// swap:- only if present & is active
type OnRumServiceClient interface {
	// posts the user request
	POST(ctx context.Context, in *IPostRequest, opts ...grpc.CallOption) (*IPostResponse, error)
	// monitor tag appends the tag if not found
	MonitorTag(ctx context.Context, in *IMonitorTagRequest, opts ...grpc.CallOption) (*IMonitorTagResponse, error)
	// release basically empties the cache
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	UpdateProfileConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error)
	UpdateKitConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error)
	UpdateServiceConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error)
	UpdateDispatcherConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error)
	UpdateEventConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error)
	GetDoc(ctx context.Context, in *IDocRequest, opts ...grpc.CallOption) (*IDocResponse, error)
}

type onRumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnRumServiceClient(cc grpc.ClientConnInterface) OnRumServiceClient {
	return &onRumServiceClient{cc}
}

func (c *onRumServiceClient) POST(ctx context.Context, in *IPostRequest, opts ...grpc.CallOption) (*IPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPostResponse)
	err := c.cc.Invoke(ctx, OnRumService_POST_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) MonitorTag(ctx context.Context, in *IMonitorTagRequest, opts ...grpc.CallOption) (*IMonitorTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IMonitorTagResponse)
	err := c.cc.Invoke(ctx, OnRumService_MonitorTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, OnRumService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) UpdateProfileConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IConfigResponse)
	err := c.cc.Invoke(ctx, OnRumService_UpdateProfileConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) UpdateKitConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IConfigResponse)
	err := c.cc.Invoke(ctx, OnRumService_UpdateKitConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) UpdateServiceConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IConfigResponse)
	err := c.cc.Invoke(ctx, OnRumService_UpdateServiceConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) UpdateDispatcherConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IConfigResponse)
	err := c.cc.Invoke(ctx, OnRumService_UpdateDispatcherConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) UpdateEventConfig(ctx context.Context, in *IConfigRequest, opts ...grpc.CallOption) (*IConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IConfigResponse)
	err := c.cc.Invoke(ctx, OnRumService_UpdateEventConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) GetDoc(ctx context.Context, in *IDocRequest, opts ...grpc.CallOption) (*IDocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDocResponse)
	err := c.cc.Invoke(ctx, OnRumService_GetDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnRumServiceServer is the server API for OnRumService service.
// All implementations must embed UnimplementedOnRumServiceServer
// for forward compatibility.
//
// OnRumService provides control plane services
// activate:- only if present & is deactive
// deactivate:- only if present & is active
// swap:- only if present & is active
type OnRumServiceServer interface {
	// posts the user request
	POST(context.Context, *IPostRequest) (*IPostResponse, error)
	// monitor tag appends the tag if not found
	MonitorTag(context.Context, *IMonitorTagRequest) (*IMonitorTagResponse, error)
	// release basically empties the cache
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	UpdateProfileConfig(context.Context, *IConfigRequest) (*IConfigResponse, error)
	UpdateKitConfig(context.Context, *IConfigRequest) (*IConfigResponse, error)
	UpdateServiceConfig(context.Context, *IConfigRequest) (*IConfigResponse, error)
	UpdateDispatcherConfig(context.Context, *IConfigRequest) (*IConfigResponse, error)
	UpdateEventConfig(context.Context, *IConfigRequest) (*IConfigResponse, error)
	GetDoc(context.Context, *IDocRequest) (*IDocResponse, error)
	mustEmbedUnimplementedOnRumServiceServer()
}

// UnimplementedOnRumServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnRumServiceServer struct{}

func (UnimplementedOnRumServiceServer) POST(context.Context, *IPostRequest) (*IPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method POST not implemented")
}
func (UnimplementedOnRumServiceServer) MonitorTag(context.Context, *IMonitorTagRequest) (*IMonitorTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MonitorTag not implemented")
}
func (UnimplementedOnRumServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedOnRumServiceServer) UpdateProfileConfig(context.Context, *IConfigRequest) (*IConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfileConfig not implemented")
}
func (UnimplementedOnRumServiceServer) UpdateKitConfig(context.Context, *IConfigRequest) (*IConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKitConfig not implemented")
}
func (UnimplementedOnRumServiceServer) UpdateServiceConfig(context.Context, *IConfigRequest) (*IConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServiceConfig not implemented")
}
func (UnimplementedOnRumServiceServer) UpdateDispatcherConfig(context.Context, *IConfigRequest) (*IConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDispatcherConfig not implemented")
}
func (UnimplementedOnRumServiceServer) UpdateEventConfig(context.Context, *IConfigRequest) (*IConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEventConfig not implemented")
}
func (UnimplementedOnRumServiceServer) GetDoc(context.Context, *IDocRequest) (*IDocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDoc not implemented")
}
func (UnimplementedOnRumServiceServer) mustEmbedUnimplementedOnRumServiceServer() {}
func (UnimplementedOnRumServiceServer) testEmbeddedByValue()                      {}

// UnsafeOnRumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnRumServiceServer will
// result in compilation errors.
type UnsafeOnRumServiceServer interface {
	mustEmbedUnimplementedOnRumServiceServer()
}

func RegisterOnRumServiceServer(s grpc.ServiceRegistrar, srv OnRumServiceServer) {
	// If the following call panics, it indicates UnimplementedOnRumServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnRumService_ServiceDesc, srv)
}

func _OnRumService_POST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).POST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_POST_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).POST(ctx, req.(*IPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_MonitorTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IMonitorTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).MonitorTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_MonitorTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).MonitorTag(ctx, req.(*IMonitorTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_UpdateProfileConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).UpdateProfileConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_UpdateProfileConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).UpdateProfileConfig(ctx, req.(*IConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_UpdateKitConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).UpdateKitConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_UpdateKitConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).UpdateKitConfig(ctx, req.(*IConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_UpdateServiceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).UpdateServiceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_UpdateServiceConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).UpdateServiceConfig(ctx, req.(*IConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_UpdateDispatcherConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).UpdateDispatcherConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_UpdateDispatcherConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).UpdateDispatcherConfig(ctx, req.(*IConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_UpdateEventConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).UpdateEventConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_UpdateEventConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).UpdateEventConfig(ctx, req.(*IConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_GetDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).GetDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_GetDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).GetDoc(ctx, req.(*IDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnRumService_ServiceDesc is the grpc.ServiceDesc for OnRumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnRumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rumrpc.OnRumService",
	HandlerType: (*OnRumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "POST",
			Handler:    _OnRumService_POST_Handler,
		},
		{
			MethodName: "MonitorTag",
			Handler:    _OnRumService_MonitorTag_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _OnRumService_Release_Handler,
		},
		{
			MethodName: "UpdateProfileConfig",
			Handler:    _OnRumService_UpdateProfileConfig_Handler,
		},
		{
			MethodName: "UpdateKitConfig",
			Handler:    _OnRumService_UpdateKitConfig_Handler,
		},
		{
			MethodName: "UpdateServiceConfig",
			Handler:    _OnRumService_UpdateServiceConfig_Handler,
		},
		{
			MethodName: "UpdateDispatcherConfig",
			Handler:    _OnRumService_UpdateDispatcherConfig_Handler,
		},
		{
			MethodName: "UpdateEventConfig",
			Handler:    _OnRumService_UpdateEventConfig_Handler,
		},
		{
			MethodName: "GetDoc",
			Handler:    _OnRumService_GetDoc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rum.proto",
}
