// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChessCoachMiscEntry struct {
	Key   *string             `json:"key,omitempty"`
	Value *ChessCoachMiscItem `json:"value,omitempty"`
}

type ChessCoachMiscItem struct {
	Title   *string `json:"title,omitempty"`
	Desc    *string `json:"desc,omitempty"`
	CanCopy *bool   `json:"canCopy,omitempty"`
	IsLink  *bool   `json:"isLink,omitempty"`
	Link    *string `json:"link,omitempty"`
	Copy    *string `json:"copy,omitempty"`
}

type ChessCoachPayload struct {
	Status  *int32  `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
}

type ChessCoachReply struct {
	Year      *string                `json:"year,omitempty"`
	Title     *string                `json:"title,omitempty"`
	Desc      *string                `json:"desc,omitempty"`
	Outro     *string                `json:"outro,omitempty"`
	Link      []*ChessCoachMiscEntry `json:"link,omitempty"`
	CopyItems []*ChessCoachMiscEntry `json:"copyItems,omitempty"`
	MiscItems []*ChessCoachMiscEntry `json:"miscItems,omitempty"`
}

type ChessStudentRequest struct {
	ID    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Query *string `json:"query,omitempty"`
}

type IConfig struct {
	Activate bool   `json:"activate"`
	Swap     *ISwap `json:"swap,omitempty"`
}

type IConfigRequest struct {
	Config         *IConfig `json:"config,omitempty"`
	Depth          int32    `json:"depth"`
	ProfileName    string   `json:"profileName"`
	KitName        string   `json:"kitName"`
	ServiceName    string   `json:"serviceName"`
	DispatcherName string   `json:"dispatcherName"`
	EventName      string   `json:"eventName"`
}

type IConfigResp struct {
	Succeed bool   `json:"succeed"`
	Error   string `json:"error"`
}

type ISwap struct {
	With    string `json:"with"`
	Current string `json:"current"`
	Swap    bool   `json:"swap"`
}

type Mutation struct {
}

type OnChessCoachReply struct {
	Information  *ChessCoachReply       `json:"information,omitempty"`
	Suggestion   *ChessCoachReply       `json:"suggestion,omitempty"`
	BestPractice *ChessCoachReply       `json:"bestPractice,omitempty"`
	MiscItems    []*ChessCoachMiscEntry `json:"miscItems,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
