// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.0
// source: rum.proto

package rumrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnRumService_POST_FullMethodName                   = "/rumrpc.OnRumService/POST"
	OnRumService_MonitorTag_FullMethodName             = "/rumrpc.OnRumService/MonitorTag"
	OnRumService_Release_FullMethodName                = "/rumrpc.OnRumService/Release"
	OnRumService_DeactivateProfile_FullMethodName      = "/rumrpc.OnRumService/DeactivateProfile"
	OnRumService_ActivateProfile_FullMethodName        = "/rumrpc.OnRumService/ActivateProfile"
	OnRumService_SwapProfile_FullMethodName            = "/rumrpc.OnRumService/SwapProfile"
	OnRumService_DeactivateKit_FullMethodName          = "/rumrpc.OnRumService/DeactivateKit"
	OnRumService_ActivateKit_FullMethodName            = "/rumrpc.OnRumService/ActivateKit"
	OnRumService_SwapKit_FullMethodName                = "/rumrpc.OnRumService/SwapKit"
	OnRumService_DeactivateService_FullMethodName      = "/rumrpc.OnRumService/DeactivateService"
	OnRumService_ActivateService_FullMethodName        = "/rumrpc.OnRumService/ActivateService"
	OnRumService_SwapService_FullMethodName            = "/rumrpc.OnRumService/SwapService"
	OnRumService_DeactivateDispatcher_FullMethodName   = "/rumrpc.OnRumService/DeactivateDispatcher"
	OnRumService_ActivateDispatcher_FullMethodName     = "/rumrpc.OnRumService/ActivateDispatcher"
	OnRumService_SwapDispatcher_FullMethodName         = "/rumrpc.OnRumService/SwapDispatcher"
	OnRumService_DeactivateEvent_FullMethodName        = "/rumrpc.OnRumService/DeactivateEvent"
	OnRumService_ActivateEvent_FullMethodName          = "/rumrpc.OnRumService/ActivateEvent"
	OnRumService_SwapEvent_FullMethodName              = "/rumrpc.OnRumService/SwapEvent"
	OnRumService_GetProfileMetadata_FullMethodName     = "/rumrpc.OnRumService/GetProfileMetadata"
	OnRumService_GetKitMetadata_FullMethodName         = "/rumrpc.OnRumService/GetKitMetadata"
	OnRumService_GetServiceMetadata_FullMethodName     = "/rumrpc.OnRumService/GetServiceMetadata"
	OnRumService_GetDispatcherMetadata_FullMethodName  = "/rumrpc.OnRumService/GetDispatcherMetadata"
	OnRumService_GetEventMetadata_FullMethodName       = "/rumrpc.OnRumService/GetEventMetadata"
	OnRumService_PullProfileMetadata_FullMethodName    = "/rumrpc.OnRumService/PullProfileMetadata"
	OnRumService_PullKitMetadata_FullMethodName        = "/rumrpc.OnRumService/PullKitMetadata"
	OnRumService_PullServiceMetadata_FullMethodName    = "/rumrpc.OnRumService/PullServiceMetadata"
	OnRumService_PullDispatcherMetadata_FullMethodName = "/rumrpc.OnRumService/PullDispatcherMetadata"
	OnRumService_PullEventMetadata_FullMethodName      = "/rumrpc.OnRumService/PullEventMetadata"
)

// OnRumServiceClient is the client API for OnRumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OnRumService provides control plane services
// activate:- only if present & is deactive
// deactivate:- only if present & is active
// swap:- only if present & is active
type OnRumServiceClient interface {
	// posts the user request
	POST(ctx context.Context, in *IPostRequest, opts ...grpc.CallOption) (*IPostResponse, error)
	// monitor tag appends the tag if not found
	MonitorTag(ctx context.Context, in *IMonitorTagRequest, opts ...grpc.CallOption) (*IMonitorTagResponse, error)
	// release basically empties the cache
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// deactivates the profile
	DeactivateProfile(ctx context.Context, in *IDeactivateProfileRequest, opts ...grpc.CallOption) (*IDeactivateProfileResponse, error)
	// activates the profile
	ActivateProfile(ctx context.Context, in *IActivateProfileRequest, opts ...grpc.CallOption) (*IActivateProfileResponse, error)
	// swaps the profile
	SwapProfile(ctx context.Context, in *ISwapProfileRequest, opts ...grpc.CallOption) (*ISwapProfileResponse, error)
	// deactivates the kit
	DeactivateKit(ctx context.Context, in *IDeactivateKitRequest, opts ...grpc.CallOption) (*IDeactivateKitResponse, error)
	// activates the kit
	ActivateKit(ctx context.Context, in *IActivateKitRequest, opts ...grpc.CallOption) (*IActivateKitResponse, error)
	// swaps the kit
	SwapKit(ctx context.Context, in *ISwapKitRequest, opts ...grpc.CallOption) (*ISwapKitResponse, error)
	// deactivates the service
	DeactivateService(ctx context.Context, in *IDeactivateServiceRequest, opts ...grpc.CallOption) (*IDeactivateServiceResponse, error)
	// activates the service
	ActivateService(ctx context.Context, in *IActivateServiceRequest, opts ...grpc.CallOption) (*IActivateServiceResponse, error)
	// swaps the service
	SwapService(ctx context.Context, in *ISwapServiceRequest, opts ...grpc.CallOption) (*ISwapServiceResponse, error)
	// deactivates the dispatcher
	DeactivateDispatcher(ctx context.Context, in *IDeactivateDispatcherRequest, opts ...grpc.CallOption) (*IDeactivateDispatcherResponse, error)
	// activates the dispatcher
	ActivateDispatcher(ctx context.Context, in *IActivateDispatcherRequest, opts ...grpc.CallOption) (*IActivateDispatcherResponse, error)
	// swaps the dispatcher
	SwapDispatcher(ctx context.Context, in *ISwapDispatcherRequest, opts ...grpc.CallOption) (*ISwapDispatcherResponse, error)
	// deactivates the event
	DeactivateEvent(ctx context.Context, in *IDeactivateEventRequest, opts ...grpc.CallOption) (*IDeactivateEventResponse, error)
	// activates the event
	ActivateEvent(ctx context.Context, in *IActivateEventRequest, opts ...grpc.CallOption) (*IActivateEventResponse, error)
	// swaps the event
	SwapEvent(ctx context.Context, in *ISwapEventRequest, opts ...grpc.CallOption) (*ISwapEventResponse, error)
	// metadatas
	// -------------------------
	// get profile metadata
	GetProfileMetadata(ctx context.Context, in *IProfileMetadataRequest, opts ...grpc.CallOption) (*IProfileMetadataResponse, error)
	// get kit metadata
	GetKitMetadata(ctx context.Context, in *IKitMetadataRequest, opts ...grpc.CallOption) (*IKitMetadataResponse, error)
	// get service metadata
	GetServiceMetadata(ctx context.Context, in *IServiceMetadataRequest, opts ...grpc.CallOption) (*IServiceMetadataResponse, error)
	// get dispatcher metadata
	GetDispatcherMetadata(ctx context.Context, in *IDispatcherMetadataRequest, opts ...grpc.CallOption) (*IDispatcherMetadataResponse, error)
	// get event metadata
	GetEventMetadata(ctx context.Context, in *IEventMetadataRequest, opts ...grpc.CallOption) (*IEventMetadataResponse, error)
	// pull profile metadata
	PullProfileMetadata(ctx context.Context, in *IPullProfileMetadataRequest, opts ...grpc.CallOption) (*IPullProfileMetadataResponse, error)
	// pull kit metadta
	PullKitMetadata(ctx context.Context, in *IPullKitMetadataRequest, opts ...grpc.CallOption) (*IPullKitMetadataResponse, error)
	// pull service metadata
	PullServiceMetadata(ctx context.Context, in *IPullServiceMetadataRequest, opts ...grpc.CallOption) (*IPullServiceMetadataResponse, error)
	// pull dispatcher metadata
	PullDispatcherMetadata(ctx context.Context, in *IPullDispatcherMetadataRequest, opts ...grpc.CallOption) (*IPullDispatcherMetadataResponse, error)
	// pull event metadata
	PullEventMetadata(ctx context.Context, in *IPullEventMetadataRequest, opts ...grpc.CallOption) (*IPullEventMetadataResponse, error)
}

type onRumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnRumServiceClient(cc grpc.ClientConnInterface) OnRumServiceClient {
	return &onRumServiceClient{cc}
}

func (c *onRumServiceClient) POST(ctx context.Context, in *IPostRequest, opts ...grpc.CallOption) (*IPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPostResponse)
	err := c.cc.Invoke(ctx, OnRumService_POST_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) MonitorTag(ctx context.Context, in *IMonitorTagRequest, opts ...grpc.CallOption) (*IMonitorTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IMonitorTagResponse)
	err := c.cc.Invoke(ctx, OnRumService_MonitorTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, OnRumService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DeactivateProfile(ctx context.Context, in *IDeactivateProfileRequest, opts ...grpc.CallOption) (*IDeactivateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeactivateProfileResponse)
	err := c.cc.Invoke(ctx, OnRumService_DeactivateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) ActivateProfile(ctx context.Context, in *IActivateProfileRequest, opts ...grpc.CallOption) (*IActivateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IActivateProfileResponse)
	err := c.cc.Invoke(ctx, OnRumService_ActivateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) SwapProfile(ctx context.Context, in *ISwapProfileRequest, opts ...grpc.CallOption) (*ISwapProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ISwapProfileResponse)
	err := c.cc.Invoke(ctx, OnRumService_SwapProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DeactivateKit(ctx context.Context, in *IDeactivateKitRequest, opts ...grpc.CallOption) (*IDeactivateKitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeactivateKitResponse)
	err := c.cc.Invoke(ctx, OnRumService_DeactivateKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) ActivateKit(ctx context.Context, in *IActivateKitRequest, opts ...grpc.CallOption) (*IActivateKitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IActivateKitResponse)
	err := c.cc.Invoke(ctx, OnRumService_ActivateKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) SwapKit(ctx context.Context, in *ISwapKitRequest, opts ...grpc.CallOption) (*ISwapKitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ISwapKitResponse)
	err := c.cc.Invoke(ctx, OnRumService_SwapKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DeactivateService(ctx context.Context, in *IDeactivateServiceRequest, opts ...grpc.CallOption) (*IDeactivateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeactivateServiceResponse)
	err := c.cc.Invoke(ctx, OnRumService_DeactivateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) ActivateService(ctx context.Context, in *IActivateServiceRequest, opts ...grpc.CallOption) (*IActivateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IActivateServiceResponse)
	err := c.cc.Invoke(ctx, OnRumService_ActivateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) SwapService(ctx context.Context, in *ISwapServiceRequest, opts ...grpc.CallOption) (*ISwapServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ISwapServiceResponse)
	err := c.cc.Invoke(ctx, OnRumService_SwapService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DeactivateDispatcher(ctx context.Context, in *IDeactivateDispatcherRequest, opts ...grpc.CallOption) (*IDeactivateDispatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeactivateDispatcherResponse)
	err := c.cc.Invoke(ctx, OnRumService_DeactivateDispatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) ActivateDispatcher(ctx context.Context, in *IActivateDispatcherRequest, opts ...grpc.CallOption) (*IActivateDispatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IActivateDispatcherResponse)
	err := c.cc.Invoke(ctx, OnRumService_ActivateDispatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) SwapDispatcher(ctx context.Context, in *ISwapDispatcherRequest, opts ...grpc.CallOption) (*ISwapDispatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ISwapDispatcherResponse)
	err := c.cc.Invoke(ctx, OnRumService_SwapDispatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) DeactivateEvent(ctx context.Context, in *IDeactivateEventRequest, opts ...grpc.CallOption) (*IDeactivateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDeactivateEventResponse)
	err := c.cc.Invoke(ctx, OnRumService_DeactivateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) ActivateEvent(ctx context.Context, in *IActivateEventRequest, opts ...grpc.CallOption) (*IActivateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IActivateEventResponse)
	err := c.cc.Invoke(ctx, OnRumService_ActivateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) SwapEvent(ctx context.Context, in *ISwapEventRequest, opts ...grpc.CallOption) (*ISwapEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ISwapEventResponse)
	err := c.cc.Invoke(ctx, OnRumService_SwapEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) GetProfileMetadata(ctx context.Context, in *IProfileMetadataRequest, opts ...grpc.CallOption) (*IProfileMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IProfileMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_GetProfileMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) GetKitMetadata(ctx context.Context, in *IKitMetadataRequest, opts ...grpc.CallOption) (*IKitMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IKitMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_GetKitMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) GetServiceMetadata(ctx context.Context, in *IServiceMetadataRequest, opts ...grpc.CallOption) (*IServiceMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IServiceMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_GetServiceMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) GetDispatcherMetadata(ctx context.Context, in *IDispatcherMetadataRequest, opts ...grpc.CallOption) (*IDispatcherMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IDispatcherMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_GetDispatcherMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) GetEventMetadata(ctx context.Context, in *IEventMetadataRequest, opts ...grpc.CallOption) (*IEventMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IEventMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_GetEventMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) PullProfileMetadata(ctx context.Context, in *IPullProfileMetadataRequest, opts ...grpc.CallOption) (*IPullProfileMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPullProfileMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_PullProfileMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) PullKitMetadata(ctx context.Context, in *IPullKitMetadataRequest, opts ...grpc.CallOption) (*IPullKitMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPullKitMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_PullKitMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) PullServiceMetadata(ctx context.Context, in *IPullServiceMetadataRequest, opts ...grpc.CallOption) (*IPullServiceMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPullServiceMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_PullServiceMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) PullDispatcherMetadata(ctx context.Context, in *IPullDispatcherMetadataRequest, opts ...grpc.CallOption) (*IPullDispatcherMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPullDispatcherMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_PullDispatcherMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onRumServiceClient) PullEventMetadata(ctx context.Context, in *IPullEventMetadataRequest, opts ...grpc.CallOption) (*IPullEventMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPullEventMetadataResponse)
	err := c.cc.Invoke(ctx, OnRumService_PullEventMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnRumServiceServer is the server API for OnRumService service.
// All implementations must embed UnimplementedOnRumServiceServer
// for forward compatibility.
//
// OnRumService provides control plane services
// activate:- only if present & is deactive
// deactivate:- only if present & is active
// swap:- only if present & is active
type OnRumServiceServer interface {
	// posts the user request
	POST(context.Context, *IPostRequest) (*IPostResponse, error)
	// monitor tag appends the tag if not found
	MonitorTag(context.Context, *IMonitorTagRequest) (*IMonitorTagResponse, error)
	// release basically empties the cache
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// deactivates the profile
	DeactivateProfile(context.Context, *IDeactivateProfileRequest) (*IDeactivateProfileResponse, error)
	// activates the profile
	ActivateProfile(context.Context, *IActivateProfileRequest) (*IActivateProfileResponse, error)
	// swaps the profile
	SwapProfile(context.Context, *ISwapProfileRequest) (*ISwapProfileResponse, error)
	// deactivates the kit
	DeactivateKit(context.Context, *IDeactivateKitRequest) (*IDeactivateKitResponse, error)
	// activates the kit
	ActivateKit(context.Context, *IActivateKitRequest) (*IActivateKitResponse, error)
	// swaps the kit
	SwapKit(context.Context, *ISwapKitRequest) (*ISwapKitResponse, error)
	// deactivates the service
	DeactivateService(context.Context, *IDeactivateServiceRequest) (*IDeactivateServiceResponse, error)
	// activates the service
	ActivateService(context.Context, *IActivateServiceRequest) (*IActivateServiceResponse, error)
	// swaps the service
	SwapService(context.Context, *ISwapServiceRequest) (*ISwapServiceResponse, error)
	// deactivates the dispatcher
	DeactivateDispatcher(context.Context, *IDeactivateDispatcherRequest) (*IDeactivateDispatcherResponse, error)
	// activates the dispatcher
	ActivateDispatcher(context.Context, *IActivateDispatcherRequest) (*IActivateDispatcherResponse, error)
	// swaps the dispatcher
	SwapDispatcher(context.Context, *ISwapDispatcherRequest) (*ISwapDispatcherResponse, error)
	// deactivates the event
	DeactivateEvent(context.Context, *IDeactivateEventRequest) (*IDeactivateEventResponse, error)
	// activates the event
	ActivateEvent(context.Context, *IActivateEventRequest) (*IActivateEventResponse, error)
	// swaps the event
	SwapEvent(context.Context, *ISwapEventRequest) (*ISwapEventResponse, error)
	// metadatas
	// -------------------------
	// get profile metadata
	GetProfileMetadata(context.Context, *IProfileMetadataRequest) (*IProfileMetadataResponse, error)
	// get kit metadata
	GetKitMetadata(context.Context, *IKitMetadataRequest) (*IKitMetadataResponse, error)
	// get service metadata
	GetServiceMetadata(context.Context, *IServiceMetadataRequest) (*IServiceMetadataResponse, error)
	// get dispatcher metadata
	GetDispatcherMetadata(context.Context, *IDispatcherMetadataRequest) (*IDispatcherMetadataResponse, error)
	// get event metadata
	GetEventMetadata(context.Context, *IEventMetadataRequest) (*IEventMetadataResponse, error)
	// pull profile metadata
	PullProfileMetadata(context.Context, *IPullProfileMetadataRequest) (*IPullProfileMetadataResponse, error)
	// pull kit metadta
	PullKitMetadata(context.Context, *IPullKitMetadataRequest) (*IPullKitMetadataResponse, error)
	// pull service metadata
	PullServiceMetadata(context.Context, *IPullServiceMetadataRequest) (*IPullServiceMetadataResponse, error)
	// pull dispatcher metadata
	PullDispatcherMetadata(context.Context, *IPullDispatcherMetadataRequest) (*IPullDispatcherMetadataResponse, error)
	// pull event metadata
	PullEventMetadata(context.Context, *IPullEventMetadataRequest) (*IPullEventMetadataResponse, error)
	mustEmbedUnimplementedOnRumServiceServer()
}

// UnimplementedOnRumServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnRumServiceServer struct{}

func (UnimplementedOnRumServiceServer) POST(context.Context, *IPostRequest) (*IPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method POST not implemented")
}
func (UnimplementedOnRumServiceServer) MonitorTag(context.Context, *IMonitorTagRequest) (*IMonitorTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorTag not implemented")
}
func (UnimplementedOnRumServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedOnRumServiceServer) DeactivateProfile(context.Context, *IDeactivateProfileRequest) (*IDeactivateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateProfile not implemented")
}
func (UnimplementedOnRumServiceServer) ActivateProfile(context.Context, *IActivateProfileRequest) (*IActivateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateProfile not implemented")
}
func (UnimplementedOnRumServiceServer) SwapProfile(context.Context, *ISwapProfileRequest) (*ISwapProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapProfile not implemented")
}
func (UnimplementedOnRumServiceServer) DeactivateKit(context.Context, *IDeactivateKitRequest) (*IDeactivateKitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateKit not implemented")
}
func (UnimplementedOnRumServiceServer) ActivateKit(context.Context, *IActivateKitRequest) (*IActivateKitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateKit not implemented")
}
func (UnimplementedOnRumServiceServer) SwapKit(context.Context, *ISwapKitRequest) (*ISwapKitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapKit not implemented")
}
func (UnimplementedOnRumServiceServer) DeactivateService(context.Context, *IDeactivateServiceRequest) (*IDeactivateServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateService not implemented")
}
func (UnimplementedOnRumServiceServer) ActivateService(context.Context, *IActivateServiceRequest) (*IActivateServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateService not implemented")
}
func (UnimplementedOnRumServiceServer) SwapService(context.Context, *ISwapServiceRequest) (*ISwapServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapService not implemented")
}
func (UnimplementedOnRumServiceServer) DeactivateDispatcher(context.Context, *IDeactivateDispatcherRequest) (*IDeactivateDispatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateDispatcher not implemented")
}
func (UnimplementedOnRumServiceServer) ActivateDispatcher(context.Context, *IActivateDispatcherRequest) (*IActivateDispatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateDispatcher not implemented")
}
func (UnimplementedOnRumServiceServer) SwapDispatcher(context.Context, *ISwapDispatcherRequest) (*ISwapDispatcherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapDispatcher not implemented")
}
func (UnimplementedOnRumServiceServer) DeactivateEvent(context.Context, *IDeactivateEventRequest) (*IDeactivateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateEvent not implemented")
}
func (UnimplementedOnRumServiceServer) ActivateEvent(context.Context, *IActivateEventRequest) (*IActivateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateEvent not implemented")
}
func (UnimplementedOnRumServiceServer) SwapEvent(context.Context, *ISwapEventRequest) (*ISwapEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwapEvent not implemented")
}
func (UnimplementedOnRumServiceServer) GetProfileMetadata(context.Context, *IProfileMetadataRequest) (*IProfileMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) GetKitMetadata(context.Context, *IKitMetadataRequest) (*IKitMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKitMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) GetServiceMetadata(context.Context, *IServiceMetadataRequest) (*IServiceMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) GetDispatcherMetadata(context.Context, *IDispatcherMetadataRequest) (*IDispatcherMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDispatcherMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) GetEventMetadata(context.Context, *IEventMetadataRequest) (*IEventMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) PullProfileMetadata(context.Context, *IPullProfileMetadataRequest) (*IPullProfileMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullProfileMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) PullKitMetadata(context.Context, *IPullKitMetadataRequest) (*IPullKitMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullKitMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) PullServiceMetadata(context.Context, *IPullServiceMetadataRequest) (*IPullServiceMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullServiceMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) PullDispatcherMetadata(context.Context, *IPullDispatcherMetadataRequest) (*IPullDispatcherMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullDispatcherMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) PullEventMetadata(context.Context, *IPullEventMetadataRequest) (*IPullEventMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullEventMetadata not implemented")
}
func (UnimplementedOnRumServiceServer) mustEmbedUnimplementedOnRumServiceServer() {}
func (UnimplementedOnRumServiceServer) testEmbeddedByValue()                      {}

// UnsafeOnRumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnRumServiceServer will
// result in compilation errors.
type UnsafeOnRumServiceServer interface {
	mustEmbedUnimplementedOnRumServiceServer()
}

func RegisterOnRumServiceServer(s grpc.ServiceRegistrar, srv OnRumServiceServer) {
	// If the following call pancis, it indicates UnimplementedOnRumServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnRumService_ServiceDesc, srv)
}

func _OnRumService_POST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).POST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_POST_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).POST(ctx, req.(*IPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_MonitorTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IMonitorTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).MonitorTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_MonitorTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).MonitorTag(ctx, req.(*IMonitorTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DeactivateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeactivateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DeactivateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DeactivateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DeactivateProfile(ctx, req.(*IDeactivateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_ActivateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IActivateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).ActivateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_ActivateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).ActivateProfile(ctx, req.(*IActivateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_SwapProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ISwapProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).SwapProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_SwapProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).SwapProfile(ctx, req.(*ISwapProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DeactivateKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeactivateKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DeactivateKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DeactivateKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DeactivateKit(ctx, req.(*IDeactivateKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_ActivateKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IActivateKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).ActivateKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_ActivateKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).ActivateKit(ctx, req.(*IActivateKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_SwapKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ISwapKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).SwapKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_SwapKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).SwapKit(ctx, req.(*ISwapKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DeactivateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeactivateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DeactivateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DeactivateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DeactivateService(ctx, req.(*IDeactivateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_ActivateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IActivateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).ActivateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_ActivateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).ActivateService(ctx, req.(*IActivateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_SwapService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ISwapServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).SwapService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_SwapService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).SwapService(ctx, req.(*ISwapServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DeactivateDispatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeactivateDispatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DeactivateDispatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DeactivateDispatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DeactivateDispatcher(ctx, req.(*IDeactivateDispatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_ActivateDispatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IActivateDispatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).ActivateDispatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_ActivateDispatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).ActivateDispatcher(ctx, req.(*IActivateDispatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_SwapDispatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ISwapDispatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).SwapDispatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_SwapDispatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).SwapDispatcher(ctx, req.(*ISwapDispatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_DeactivateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDeactivateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).DeactivateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_DeactivateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).DeactivateEvent(ctx, req.(*IDeactivateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_ActivateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IActivateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).ActivateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_ActivateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).ActivateEvent(ctx, req.(*IActivateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_SwapEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ISwapEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).SwapEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_SwapEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).SwapEvent(ctx, req.(*ISwapEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_GetProfileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IProfileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).GetProfileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_GetProfileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).GetProfileMetadata(ctx, req.(*IProfileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_GetKitMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IKitMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).GetKitMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_GetKitMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).GetKitMetadata(ctx, req.(*IKitMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_GetServiceMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IServiceMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).GetServiceMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_GetServiceMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).GetServiceMetadata(ctx, req.(*IServiceMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_GetDispatcherMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDispatcherMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).GetDispatcherMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_GetDispatcherMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).GetDispatcherMetadata(ctx, req.(*IDispatcherMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_GetEventMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IEventMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).GetEventMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_GetEventMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).GetEventMetadata(ctx, req.(*IEventMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_PullProfileMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPullProfileMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).PullProfileMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_PullProfileMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).PullProfileMetadata(ctx, req.(*IPullProfileMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_PullKitMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPullKitMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).PullKitMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_PullKitMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).PullKitMetadata(ctx, req.(*IPullKitMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_PullServiceMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPullServiceMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).PullServiceMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_PullServiceMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).PullServiceMetadata(ctx, req.(*IPullServiceMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_PullDispatcherMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPullDispatcherMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).PullDispatcherMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_PullDispatcherMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).PullDispatcherMetadata(ctx, req.(*IPullDispatcherMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnRumService_PullEventMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPullEventMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnRumServiceServer).PullEventMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnRumService_PullEventMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnRumServiceServer).PullEventMetadata(ctx, req.(*IPullEventMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnRumService_ServiceDesc is the grpc.ServiceDesc for OnRumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnRumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rumrpc.OnRumService",
	HandlerType: (*OnRumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "POST",
			Handler:    _OnRumService_POST_Handler,
		},
		{
			MethodName: "MonitorTag",
			Handler:    _OnRumService_MonitorTag_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _OnRumService_Release_Handler,
		},
		{
			MethodName: "DeactivateProfile",
			Handler:    _OnRumService_DeactivateProfile_Handler,
		},
		{
			MethodName: "ActivateProfile",
			Handler:    _OnRumService_ActivateProfile_Handler,
		},
		{
			MethodName: "SwapProfile",
			Handler:    _OnRumService_SwapProfile_Handler,
		},
		{
			MethodName: "DeactivateKit",
			Handler:    _OnRumService_DeactivateKit_Handler,
		},
		{
			MethodName: "ActivateKit",
			Handler:    _OnRumService_ActivateKit_Handler,
		},
		{
			MethodName: "SwapKit",
			Handler:    _OnRumService_SwapKit_Handler,
		},
		{
			MethodName: "DeactivateService",
			Handler:    _OnRumService_DeactivateService_Handler,
		},
		{
			MethodName: "ActivateService",
			Handler:    _OnRumService_ActivateService_Handler,
		},
		{
			MethodName: "SwapService",
			Handler:    _OnRumService_SwapService_Handler,
		},
		{
			MethodName: "DeactivateDispatcher",
			Handler:    _OnRumService_DeactivateDispatcher_Handler,
		},
		{
			MethodName: "ActivateDispatcher",
			Handler:    _OnRumService_ActivateDispatcher_Handler,
		},
		{
			MethodName: "SwapDispatcher",
			Handler:    _OnRumService_SwapDispatcher_Handler,
		},
		{
			MethodName: "DeactivateEvent",
			Handler:    _OnRumService_DeactivateEvent_Handler,
		},
		{
			MethodName: "ActivateEvent",
			Handler:    _OnRumService_ActivateEvent_Handler,
		},
		{
			MethodName: "SwapEvent",
			Handler:    _OnRumService_SwapEvent_Handler,
		},
		{
			MethodName: "GetProfileMetadata",
			Handler:    _OnRumService_GetProfileMetadata_Handler,
		},
		{
			MethodName: "GetKitMetadata",
			Handler:    _OnRumService_GetKitMetadata_Handler,
		},
		{
			MethodName: "GetServiceMetadata",
			Handler:    _OnRumService_GetServiceMetadata_Handler,
		},
		{
			MethodName: "GetDispatcherMetadata",
			Handler:    _OnRumService_GetDispatcherMetadata_Handler,
		},
		{
			MethodName: "GetEventMetadata",
			Handler:    _OnRumService_GetEventMetadata_Handler,
		},
		{
			MethodName: "PullProfileMetadata",
			Handler:    _OnRumService_PullProfileMetadata_Handler,
		},
		{
			MethodName: "PullKitMetadata",
			Handler:    _OnRumService_PullKitMetadata_Handler,
		},
		{
			MethodName: "PullServiceMetadata",
			Handler:    _OnRumService_PullServiceMetadata_Handler,
		},
		{
			MethodName: "PullDispatcherMetadata",
			Handler:    _OnRumService_PullDispatcherMetadata_Handler,
		},
		{
			MethodName: "PullEventMetadata",
			Handler:    _OnRumService_PullEventMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rum.proto",
}
